/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:d3da58ee-46b8-4b00-aa3a-a14c37b64aa7",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_KiJzP2dH5",
    "aws_user_pools_web_client_id": "3pf37ngd57hsk9ld12aha9bm2f",
    "oauth": {},
    "federationTarget": "COGNITO_IDENTITY_POOLS",
    "aws_cognito_login_mechanisms": [
        "FACEBOOK",
        "GOOGLE",
        "AMAZON"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OPTIONAL",
    "aws_cognito_mfa_types": [
        "TOTP"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_UPPERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS"
        ]
    },
    "aws_appsync_graphqlEndpoint": "https://qt6manqtzbhkvd6tcxvchusmyq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-6zfuocqmhvecrfkng7hx2oipni",
    "aws_cloud_logic_custom": [
        {
            "name": "image",
            "endpoint": "https://95i5crqja0.execute-api.us-east-1.amazonaws.com/tmhprod",
            "region": "us-east-1"
        },
        {
            "name": "AdminQueries",
            "endpoint": "https://tchlhrimna.execute-api.us-east-1.amazonaws.com/tmhprod",
            "region": "us-east-1"
        }
    ],
    "aws_content_delivery_bucket": "heeetingouse-20190312104205-hostingbucket-tmhprod",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d3ovx9jsa9o5gy.cloudfront.net",
    "aws_mobile_analytics_app_id": "20b026ebefc445dd82e5a853dff62770",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_user_files_s3_bucket": "themeetinghouse-usercontentstoragetmhusercontent-tmhprod",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
